#!/bin/bash
echo "Hello world!!3456"
echo "This line is from feature branch"
echo "apt update -y " # From Feature Branch
echo "This line is from master branch, changes in modified"
echo "New lines"
echo "Lines from remore repo"
echo "Lines to check diff cmd"
